### PR TITLE
SB/32-Unsubscribe

### PR DESCRIPTION
**Pull request by shanedbutler**
# Description

Functionality added for a user to unsubscribe from an author.

# Testing Instructions

`git checkout SB/32-Unsubscribe`

1. Login with any user
2. Navigate to Posts via navbar
3. Navigate to the post details page by clicking the tile of any post
4. Use the "Subscribe to Author" link to subscribe if you haven't yet
5. Navigate to Home via the navbar
6. Ensure that the author's posts that you subscribed to are listed
7. Click on a post title to view the post details page and click unsubscribe 
8. Verify that you've been unsubscribed from that author by either querying the database or ensuring that you cannot see the authors posts in the Home post lists.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by nthi — COMMENTED** [review]
Subscribe is working fine, but I'm having trouble unsubscribing.

I poked around with dev tools and noticed that when I use Components > Element selector to hover over the links on that card, all the links highlight individually except for "Unsubscribe from Author" which blues out the entire links div. Not sure if that helps, but I thought I'd mention it.

The page knows the state is unsubscribed (hook for sub/unsub is "true" and I can toggle it in dev tools to see the state and link change), but I don't see any changes when I click the link on page (no state change, link stays labeled "Unsubscribe...")

**Comment by shanedbutler** [comment]
> Subscribe is working fine, but I'm having trouble unsubscribing.
> 
> I poked around with dev tools and noticed that when I use Components > Element selector to hover over the links on that card, all the links highlight individually except for "Unsubscribe from Author" which blues out the entire links div. Not sure if that helps, but I thought I'd mention it.
> 
> The page knows the state is unsubscribed (hook for sub/unsub is "true" and I can toggle it in dev tools to see the state and link change), but I don't see any changes when I click the link on page (no state change, link stays labeled "Unsubscribe...")



> Subscribe is working fine, but I'm having trouble unsubscribing.
> 
> I poked around with dev tools and noticed that when I use Components > Element selector to hover over the links on that card, all the links highlight individually except for "Unsubscribe from Author" which blues out the entire links div. Not sure if that helps, but I thought I'd mention it.
> 
> The page knows the state is unsubscribed (hook for sub/unsub is "true" and I can toggle it in dev tools to see the state and link change), but I don't see any changes when I click the link on page (no state change, link stays labeled "Unsubscribe...")

Hm, I'm not able to reproduce any issues. Can I ask how you are confirming that the subscription has ended? If you query the database, the subscription entry stays, but it has a end date. The backend repository method then filters out subbed posts that contain a non-null end date column so those posts do not populate on the Home ("/") route.

**Review by nthi — APPROVED** [review]
This does work perfectly!

**Review by ToniJBaker — APPROVED** [review]

**Review by robert-brunner — APPROVED** [review]
Worked for me

**Pull request merged**
